<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>josm-geotools-wfs</groupId>
  <artifactId>josm-geotools-wfs</artifactId>
  <version>27.1.1</version>
  <name>Josm geotools wfs</name>
  <description>Extend the josm geotools plug-in with WFS functionality</description>
  <properties>
    <geotools.version>27.1</geotools.version>
    <josm.version>19277</josm.version>
    <maven.compiler.version>3.14.1</maven.compiler.version>
    <maven.compiler.release>17</maven.compiler.release>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
  </properties>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler.version}</version>
        <configuration>
          <release>${maven.compiler.release}</release>
          <parameters>true</parameters>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.6</version>
        <executions>
          <execution>
        <id>copy-dependencies</id>
        <phase>package</phase>
        <goals>
          <goal>copy-dependencies</goal>
        </goals>
        <configuration>
          <outputDirectory>lib</outputDirectory>
          <overWriteIfNewer>true</overWriteIfNewer>
          <excludeGroupIds>net.sf.geographiclib,commons-pool, commons-beanutils,
            commons-logging,hsqldb,javax.media,net.java.dev.jsr-275,it.geosolutions.imageio-ext,
            com.vividsolutions,it.geosolutions.jaiext,org.jaitools,org.ejml
          </excludeGroupIds>
          <excludeArtifactIds>gt-api, gt-coverage,gt-data,gt-epsg-extension,
            gt-hsql,gt-geotiff,gt-main,gt-opengis,gt-referencing,gt-metadata,
            gt-shapefile,jdom
          </excludeArtifactIds>
        </configuration>
      </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>org.geotools</groupId>
      <artifactId>gt-wfs-ng</artifactId>
      <version>${geotools.version}</version>
    </dependency>
    <dependency>
      <groupId>org.openstreetmap.josm</groupId>
      <artifactId>josm</artifactId>
      <version>${josm.version}</version>
    </dependency>
  </dependencies>
    <repositories>
    <repository>
      <id>josm</id>
      <name>Josm repository</name>
      <url>https://josm.openstreetmap.de/nexus/content/repositories/releases/</url>
    </repository>
    <repository>
      <id>osgeo</id>
      <name>Osgeo repository</name>
      <url>https://repo.osgeo.org/repository/geotools-releases/</url>
    </repository>
  </repositories>
</project>